name: Update feed

on:
  push:
    branch:
      - master
  schedule:
    - cron: '0 8 * */1 *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: build
        run: go build ./...
      - name: deploy
        run: ./komisan19
      - name: Checkout
        uses: actions/checkout@master
      - name: git setting
        run: |
          git config --local user.email "komiyama6219@gmail.com"
          git config --local user.name "komisan19"
      - name: Commit files
        run: |
          git add .
          if ! git diff --exit-code --quiet
          then
            git commit -m "Update feed"
            git push origin main -f
          fi
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
